apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-hello
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-hello
  template:
    metadata:
      labels:
        app: apache-hello
    spec:
      containers:
      - name: apache
        image: httpd:alpine
        ports:
        - containerPort: 80
        # Quick inline hello world via command override
        command: ["/bin/sh", "-c"]
        args:
          - echo "<html><body><h1>Hello World!</h1><p>Running Apache HTTPD static page in k8s.</p></body></html>" > /usr/local/apache2/htdocs/index.html && httpd-foreground
---
apiVersion: v1
kind: Service
metadata:
  name: apache-hello-service
  namespace: hello-world
spec:
  selector:
    app: apache-hello
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
