#!/bin/bash

# Script to validate WordPress service
# Starts port-forward, checks HTTP status and HTML content for "Sample post #"

set -e

# Local forward port mapping
PORT="${PORT:-18080}"
URL="http://127.0.0.1:${PORT}/"
TIMEOUT="${TIMEOUT:-10}"

# WordPress seed id to identify exact wordpress deployment
# The ID is generated by wordpress-install Job and is part of post title
# Example 886 for sample post title "Sample post #886"
WORDPRESS_SEED_ID="${WORDPRESS_SEED_ID:-}"


echo "# Validating WordPress service"
echo "# Using kubectl context: $(kubectl config current-context)"
echo ""

# Check if MySQL deployment exists and is ready
echo "Checking MySQL deployment status..."
if ! kubectl get deployment wordpress-mysql &>/dev/null; then
    echo "✗ FAILED: Deployment 'wordpress-mysql' not found"
    exit 1
fi

echo "Waiting for deployment 'wordpress-mysql' to be ready..."
if ! kubectl wait --for=condition=available --timeout=120s deployment/wordpress-mysql; then
    echo "✗ FAILED: Deployment 'wordpress-mysql' did not become ready within 120 seconds"
    kubectl get deployment wordpress-mysql
    kubectl get pods -l tier=mysql
    exit 1
fi
echo "✓ PASSED: Deployment 'wordpress-mysql' is ready"

# Check if WordPress deployment exists and is ready
echo "Checking WordPress deployment status..."
if ! kubectl get deployment wordpress &>/dev/null; then
    echo "✗ FAILED: Deployment 'wordpress' not found"
    exit 1
fi

echo "Waiting for deployment 'wordpress' to be ready..."
if ! kubectl wait --for=condition=available --timeout=120s deployment/wordpress; then
    echo "✗ FAILED: Deployment 'wordpress' did not become ready within 120 seconds"
    kubectl get deployment wordpress
    kubectl get pods -l tier=frontend
    exit 1
fi
echo "✓ PASSED: Deployment 'wordpress' is ready"

# Check if MySQL service exists
echo "Checking MySQL service presence..."
if ! kubectl get service wordpress-mysql &>/dev/null; then
    echo "✗ FAILED: Service 'wordpress-mysql' not found"
    exit 1
fi
echo "✓ PASSED: Service 'wordpress-mysql' exists"

# Check if WordPress service exists
echo "Checking WordPress service presence..."
if ! kubectl get service wordpress &>/dev/null; then
    echo "✗ FAILED: Service 'wordpress' not found"
    exit 1
fi
echo "✓ PASSED: Service 'wordpress' exists"

# Start port-forward in background
echo "Starting port-forward on port ${PORT}..."
kubectl port-forward svc/wordpress ${PORT}:80 &
PF_PID=$!

# Cleanup function to kill port-forward on exit
cleanup() {
    echo ""
    echo "Stopping port-forward (PID: $PF_PID)..."
    kill $PF_PID 2>/dev/null || true
}
trap cleanup EXIT

# Wait for port-forward to be ready
echo "Waiting for port-forward to be ready..."
sleep 3

# Perform curl request and capture HTTP status and response body
echo "Performing HTTP request to ${URL}..."
HTTP_RESPONSE=$(curl -s -w "\n%{http_code}" --max-time "$TIMEOUT" "$URL" 2>&1)

# Extract HTTP status code (last line)
HTTP_STATUS=$(echo "$HTTP_RESPONSE" | tail -n 1)

# Extract response body (everything except last line)
RESPONSE_BODY=$(echo "$HTTP_RESPONSE" | head -n -1)

echo "HTTP Status: $HTTP_STATUS"

# Check HTTP status
if [ "$HTTP_STATUS" != "200" ]; then
    echo "✗ FAILED: Expected HTTP status 200, got $HTTP_STATUS"
    exit 1
fi

echo "✓ PASSED: HTTP status is 200"

# Track validation failures
VALIDATION_FAILED=0

# Check for "Hello from k8s" in HTML content
if echo "$RESPONSE_BODY" | grep -q "Hello from k8s"; then
    echo "✓ PASSED: Found 'Hello from k8s' in HTML content"
else
    echo "✗ FAILED: Could not find 'Hello from k8s' in HTML content"
    VALIDATION_FAILED=1
fi

# Check for "Sample post #" in HTML content
if echo "$RESPONSE_BODY" | grep -q "Sample post #"; then
    echo "✓ PASSED: Found _some_ 'Sample post #' in HTML content"
else
    echo "✗ FAILED: Could not find any 'Sample post #' in HTML content"
    VALIDATION_FAILED=1
fi

# Check for specific WordPress seed ID if provided
if [ -n "$WORDPRESS_SEED_ID" ]; then
    if echo "$RESPONSE_BODY" | grep -q "#${WORDPRESS_SEED_ID}"; then
        echo "✓ PASSED: Found exact '#${WORDPRESS_SEED_ID}' in HTML content"
    else
        echo "✗ FAILED: Could not find exact #${WORDPRESS_SEED_ID} in HTML content."
        echo "           Hint: Maybe it is a different Wordpress deployment?"
        VALIDATION_FAILED=1
    fi
else
    echo ". SKIPPING: WORDPRESS_SEED_ID not provided."
fi

# Final result
echo ""
if [ "$VALIDATION_FAILED" -eq 0 ]; then
    echo "✓ All validation checks passed!"
    exit 0
else
    echo "✗ Some validation checks failed"
    echo ""
    echo "Response preview (first 500 chars):"
    echo "$RESPONSE_BODY" | head -c 500
    echo ""
    exit 1
fi
