apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-install
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pv-claim   # same PVC as wordpress Deployment
      containers:
        - name: wp-install
          image: wordpress:cli-2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: wordpress-mysql
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: MYSQL_WORDPRESS_PASSWORD
            - name: WORDPRESS_SITE_URL
              value: http://wordpress-k8s.example.local
            - name: WORDPRESS_SITE_TITLE
              value: "My WordPress Site on k8s"
            - name: WORDPRESS_ADMIN_USER
              value: admin
            - name: WORDPRESS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secrets
                  key: WORDPRESS_ADMIN_PASSWORD
            - name: WORDPRESS_ADMIN_EMAIL
              value: admin@wordpress-k8s.example.local

          command:
            - bash
          args:
            - -lc
            - |
              set -e
              cd /var/www/html

              echo "Waiting for MySQL on ${WORDPRESS_DB_HOST}:3306..."
              for i in $(seq 1 60); do
                if mariadb-admin ping -h"${WORDPRESS_DB_HOST}" -u"${WORDPRESS_DB_USER}" -p"${WORDPRESS_DB_PASSWORD}" --ssl=false --silent; then
                  echo "MySQL is up."
                  break
                fi
                echo "MySQL not ready yet (attempt: $i)..."
                sleep 5
              done

              if ! mariadb-admin ping -h"${WORDPRESS_DB_HOST}" -u"${WORDPRESS_DB_USER}" -p"${WORDPRESS_DB_PASSWORD}" --ssl=false --silent; then
                echo "MySQL did not become ready within the timeout."
                exit 1
              fi

              # Make sure WordPress core is present on the volume
              if [ ! -f wp-load.php ]; then
                echo "WordPress core not found on the volume. Downloading..."
                wp core download --allow-root
              fi

              # Create wp-config.php if missing
              if [ ! -f wp-config.php ]; then
                echo "Creating wp-config.php..."
                wp config create \
                  --dbname="${WORDPRESS_DB_NAME}" \
                  --dbuser="${WORDPRESS_DB_USER}" \
                  --dbpass="${WORDPRESS_DB_PASSWORD}" \
                  --dbhost="${WORDPRESS_DB_HOST}" \
                  --allow-root
              fi

              # Idempotent install
              if wp core is-installed --allow-root >/dev/null 2>&1; then
                echo "WordPress is already installed. Nothing to do."
                exit 0
              fi

              echo "Running wp core install..."
              wp core install \
                --url="${WORDPRESS_SITE_URL}" \
                --title="${WORDPRESS_SITE_TITLE}" \
                --admin_user="${WORDPRESS_ADMIN_USER}" \
                --admin_password="${WORDPRESS_ADMIN_PASSWORD}" \
                --admin_email="${WORDPRESS_ADMIN_EMAIL}" \
                --skip-email \
                --allow-root

              echo "Creating sample post..."
              wp post create \
                --post_type=post \
                --post_status=publish \
                --post_title="Sample post #$RANDOM" \
                --post_content="Hello from k8s, this is a random post content: $(openssl rand -base64 200 | tr -cs 'a-zA-Z' ' ' | xargs)"

              echo "Done. WordPress has been installed."
